"""species table

Revision ID: cf756b060e35
Revises: 
Create Date: 2020-07-06 16:46:08.163026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf756b060e35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    species_table = op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_type', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(species_table,
        [
        {'id': 1, 'species_type': 'Human'},
        {'id': 2, 'species_type': 'Driod'},
        {'id': 3, 'species_type': 'Wookie'},
        {'id': 4, 'species_type': 'Rodian'},
        {'id': 5, 'species_type': 'Hutt'},
        {'id': 6, 'species_type': "Yoda's Species"},
        {'id': 7, 'species_type': 'Trandoshan'},
        {'id': 8, 'species_type': 'Mon Calamari'},
        {'id': 9, 'species_type': 'Ewok'},
        {'id': 10, 'species_type': 'Sullustan'},
        {'id': 11, 'species_type': 'Neimodian'},
        {'id': 12, 'species_type': 'Gungan'},
        {'id': 13, 'species_type': 'Toydarian'},
        {'id': 14, 'species_type': 'Dug'},
        {'id': 15, 'species_type': "Twi'lek"},
        {'id': 16, 'species_type': 'Aleena'},
        {'id': 17, 'species_type': 'Vulptereen'},
        {'id': 18, 'species_type': 'Xexto'},
        {'id': 19, 'species_type': 'Toong'},
        {'id': 20, 'species_type': 'Cerean'},
        {'id': 21, 'species_type': 'Nautolan'},
        {'id': 22, 'species_type': 'Zabrak'},
        {'id': 23, 'species_type': 'Tholothian'},
        {'id': 24, 'species_type': 'Iktotchi'},
        {'id': 25, 'species_type': 'Quermian'},
        {'id': 26, 'species_type': 'Kel Dor'},
        {'id': 27, 'species_type': 'Chagrian'},
        {'id': 28, 'species_type': 'Geonosian'},
        {'id': 29, 'species_type': 'Mirialan'},
        {'id': 30, 'species_type': 'Clawdite'},
        {'id': 31, 'species_type': 'Besalisk'},
        {'id': 32, 'species_type': 'Kaminoan'},
        {'id': 33, 'species_type': 'Skakoan'},
        {'id': 34, 'species_type': 'Muun'},
        {'id': 35, 'species_type': 'Togruta'},
        {'id': 36, 'species_type': 'Kaleesh'},
        {'id': 37, 'species_type': "Pau'an"}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species')
    # ### end Alembic commands ###
