"""create migrations

Revision ID: 789b401726d6
Revises: 
Create Date: 2020-07-05 14:17:13.153060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789b401726d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shiptypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('starship_class', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('hyperdrive_rating', sa.Float(), nullable=False),
    sa.Column('mglt', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=False),
    sa.Column('passenger', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.Integer(), nullable=False),
    sa.Column('consumables', sa.Integer(), nullable=False),
    sa.Column('cost_credits', sa.Integer(), nullable=False),
    sa.Column('ship_image', sa.String(length=150), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    species_table = op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_type', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('species', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('faction', sa.Boolean(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('user_image', sa.String(length=150), nullable=False),
    sa.Column('force_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_type', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=75), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('lightyears_traveled', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('for_sale', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ship_type'], ['shiptypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.Integer(), nullable=True),
    sa.Column('seller', sa.Integer(), nullable=True),
    sa.Column('starship', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller'], ['users.id'], ),
    sa.ForeignKeyConstraint(['starship'], ['starships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(species_table, 
        [
        {"id": 1, "species_type": "Human"},
        { "id":2, "species_type":"Driod"},
        {"id": 3, "species_type": "Wookie"},
        {"id": 4, "species_type": "Rodian"},
        {"id": 5, "species_type": "Hutt"},
        {"id": 6, "species_type": "Yoda's Species"},
        {'id': 7, 'species_type': 'Trandoshan'},
        {'id': 8, 'species_type': 'Mon Calamari'},
        {'id': 9, 'species_type': 'Ewok'},
        {'id': 10, 'species_type': 'Sullustan'},
        {'id': 11, 'species_type': 'Neimodian'},
        {'id': 12, 'species_type': 'Gungan'},
        {'id': 13, 'species_type': 'Toydarian'},
        {'id': 14, 'species_type': 'Dug'},
        {'id': 15, 'species_type': "Twi'lek"},
        {'id': 16, 'species_type': 'Aleena'},
        {'id': 17, 'species_type': 'Vulptereen'},
        {'id': 18, 'species_type': 'Xexto'},
        {'id': 19, 'species_type': 'Toong'},
        {'id': 20, 'species_type': 'Cerean'},
        {'id': 21, 'species_type': 'Nautolan'},
        {'id': 22, 'species_type': 'Zabrak'},
        {'id': 23, 'species_type': 'Tholothian'},
        {'id': 24, 'species_type': 'Iktotchi'},
        {'id': 25, 'species_type': 'Quermian'},
        {'id': 26, 'species_type': 'Kel Dor'},
        {'id': 27, 'species_type': 'Chagrian'},
        {'id': 28, 'species_type': 'Geonosian'},
        {'id': 29, 'species_type': 'Mirialan'},
        {'id': 30, 'species_type': 'Clawdite'},
        {'id': 31, 'species_type': 'Besalisk'},
        {'id': 32, 'species_type': 'Kaminoan'},
        {'id': 33, 'species_type': 'Skakoan'},
        {'id': 34, 'species_type': 'Muun'},
        {'id': 35, 'species_type': 'Togruta'},
        {'id': 36, 'species_type': 'Kaleesh'},
        {'id': 37, 'species_type': "Pau'an"}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('starships')
    op.drop_table('users')
    op.drop_table('species')
    op.drop_table('shiptypes')
    # ### end Alembic commands ###
