"""transactions table

Revision ID: 88bab2df687a
Revises: db3f0ede48f5
Create Date: 2020-07-06 17:03:48.974233

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '88bab2df687a'
down_revision = 'db3f0ede48f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    transactions_table = op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.Integer(), nullable=True),
    sa.Column('seller', sa.Integer(), nullable=True),
    sa.Column('starship', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.BigInteger(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller'], ['users.id'], ),
    sa.ForeignKeyConstraint(['starship'], ['starships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(transactions_table,
        [
        {'buyer': 14, 'seller': 25, 'starship': 1, 'sale_price': 1000000, 'sale_date': datetime.datetime.now()},
        {'buyer': 12, 'seller': 21, 'starship': 2, 'sale_price': 1000000000000, 'sale_date': datetime.datetime.now()},
        {'buyer': 10, 'seller': 20, 'starship': 3, 'sale_price': 220000, 'sale_date': datetime.datetime.now()},
        {'buyer': 4, 'seller': 21, 'starship': 4, 'sale_price': 119999, 'sale_date': datetime.datetime.now()},
        {'buyer': 27, 'seller': 28, 'starship': 5, 'sale_price': 100000000, 'sale_date': datetime.datetime.now()},
        {'buyer': 22, 'seller': 24, 'starship': 6, 'sale_price': 249999, 'sale_date': datetime.datetime.now()},
        {'buyer': 18, 'seller': 27, 'starship': 7, 'sale_price': 105000, 'sale_date': datetime.datetime.now()},
        {'buyer': 21, 'seller': 12, 'starship': 8, 'sale_price': 157000, 'sale_date': datetime.datetime.now()},
        {'buyer': 14, 'seller': 4, 'starship': 9, 'sale_price': 251000, 'sale_date': datetime.datetime.now()},
        {'buyer': 4, 'seller': 21, 'starship': 10, 'sale_price': 150000, 'sale_date': datetime.datetime.now()},
        {'buyer': 25, 'seller': 20, 'starship': 11, 'sale_price': 430000, 'sale_date': datetime.datetime.now()},
        {'buyer': 24, 'seller': 22, 'starship': 12, 'sale_price': 148005, 'sale_date': datetime.datetime.now()},
        {'buyer': 17, 'seller': 4, 'starship': 13, 'sale_price': 224725, 'sale_date': datetime.datetime.now()},
        {'buyer': 5, 'seller': 27, 'starship': 14, 'sale_price': 425000, 'sale_date': datetime.datetime.now()},
        {'buyer': 31, 'seller': 5, 'starship': 15, 'sale_price': 625000, 'sale_date': datetime.datetime.now()},
        {'buyer': 9, 'seller': 28, 'starship': 16, 'sale_price': 215999, 'sale_date': datetime.datetime.now()},
        {'buyer': 30, 'seller': 21, 'starship': 17, 'sale_price': 255999, 'sale_date': datetime.datetime.now()},
        {'buyer': 33, 'seller': 32, 'starship': 18, 'sale_price': 182575, 'sale_date': datetime.datetime.now()},
        {'buyer': 29, 'seller': 27, 'starship': 19, 'sale_price': 190500, 'sale_date': datetime.datetime.now()},
        {'buyer': 28, 'seller': 11, 'starship': 20, 'sale_price': 65000, 'sale_date': datetime.datetime.now()}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
